FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages

COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json

COPY ./package-lock.json ./package-lock.json

COPY ./turbo.json ./turbo.json

COPY ./apps/http-server ./apps/http-server

RUN bun install

RUN bun run db:generate

EXPOSE 3001

CMD ["bun","run","start:http-server"]


