name: Deploy the backend
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: msukhlani20/todo-app-backend:${{github.sha}}

      - name: Deploy to the VM
        run: |
          echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
          chmod 700 /home/runner/ssh_key   
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@52.66.239.38 -t "sudo docker stop user_backend && sudo docker container prune --force && sudo docker run --name user_backend -d -p 3001:3001 msukhlani20/todo-app-backend:${{ github.sha }}"
